import '../pack_detail_composer_screen/widgets/listtitle_item_widget.dart';import 'controller/pack_detail_composer_controller.dart';import 'models/listtitle_item_model.dart';import 'package:flutter/material.dart';import 'package:pbm_care/core/app_export.dart';import 'package:pbm_care/widgets/custom_bottom_bar.dart';import 'package:pbm_care/widgets/custom_button.dart';class PackDetailComposerScreen extends GetWidget<PackDetailComposerController> {const PackDetailComposerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.pinkA100, body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, padding: getPadding(left: 4, top: 30, right: 4, bottom: 30), decoration: AppDecoration.brand, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: getPadding(left: 12, top: 17, bottom: 5), child: Text("lbl_composer".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtOpenSansRomanBold34)), CustomButton(height: getVerticalSize(52), width: getHorizontalSize(148), text: "lbl_go_to_dashboard".tr, margin: getMargin(top: 18), variant: ButtonVariant.FillBluegray90001, onTap: () {onTapGotodashboard();})])), Expanded(child: Padding(padding: getPadding(top: 10), child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(17));}, itemCount: controller.packDetailComposerModelObj.value.listtitleItemList.value.length, itemBuilder: (context, index) {ListtitleItemModel model = controller.packDetailComposerModelObj.value.listtitleItemList.value[index]; return ListtitleItemWidget(model);}))))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Volume: return "/"; case BottomBarEnum.Sort: return "/"; case BottomBarEnum.Vuesaxlinearaddpinka100: return "/"; case BottomBarEnum.Car: return "/"; case BottomBarEnum.User: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {default: return DefaultWidget();} } 
/// Navigates to the upcomingBookingFourScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the upcomingBookingFourScreen.
onTapGotodashboard() { Get.toNamed(AppRoutes.upcomingBookingFourScreen, ); } 
 }
