import 'controller/routinefinishedpage_controller.dart';import 'package:flutter/material.dart';import 'package:pbm_care/core/app_export.dart';import 'package:pbm_care/widgets/app_bar/appbar_image.dart';import 'package:pbm_care/widgets/app_bar/appbar_subtitle.dart';import 'package:pbm_care/widgets/app_bar/custom_app_bar.dart';import 'package:pbm_care/widgets/custom_text_form_field.dart';class RoutinefinishedpageScreen extends GetWidget<RoutinefinishedpageController> {const RoutinefinishedpageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: ColorConstant.gray100, appBar: CustomAppBar(height: getVerticalSize(110), leadingWidth: 80, leading: AppbarImage(height: getSize(48), width: getSize(48), svgPath: ImageConstant.imgMdiarrowleft, margin: getMargin(left: 32, top: 19), onTap: () {onTapMdiarrowleft2();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_last_activity".tr, margin: getMargin(bottom: 22)), actions: [AppbarImage(height: getSize(40), width: getSize(40), svgPath: ImageConstant.imgClose, margin: getMargin(left: 32, right: 32, bottom: 26))]), body: Container(width: getHorizontalSize(411), padding: getPadding(left: 39, top: 1, right: 39, bottom: 1), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(margin: getMargin(left: 2, right: 2), padding: getPadding(left: 100, top: 8, right: 100, bottom: 8), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgFlag, height: getSize(24), width: getSize(24), margin: getMargin(top: 1, bottom: 268)), Padding(padding: getPadding(left: 10, bottom: 264), child: Text("lbl_play".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtOpenSans24Black90001))])), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: controller.describeactivitController, hintText: "msg_describe_activities".tr, margin: getMargin(top: 32), textInputAction: TextInputAction.done), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: getMargin(top: 32), color: ColorConstant.pink400, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.circleBorder48), child: Container(height: getSize(96), width: getSize(96), padding: getPadding(left: 25, top: 30, right: 25, bottom: 30), decoration: AppDecoration.fillPink400.copyWith(borderRadius: BorderRadiusStyle.circleBorder48), child: Stack(children: [CustomImageView(svgPath: ImageConstant.imgCheckmark, height: getVerticalSize(33), width: getHorizontalSize(43), alignment: Alignment.center)]))), Container(margin: getMargin(left: 49, top: 32, right: 49, bottom: 5), padding: getPadding(left: 16, top: 15, right: 16, bottom: 15), decoration: AppDecoration.outlineBlack90059.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Text("lbl_new_routine".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtOpenSansLight24Black90059), CustomImageView(svgPath: ImageConstant.imgPlusBlack900, height: getSize(24), width: getSize(24), margin: getMargin(left: 40, top: 4, bottom: 4))]))])))); } 
/// Navigates to the homeScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the homeScreen.
onTapMdiarrowleft2() { Get.toNamed(AppRoutes.homeScreen, ); } 
 }
