# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# Pods for Runner
pod 'audioplayers', :target => 'Runner'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
