name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: App Build
          path: build/app/outputs/apk/release/app-release.apk

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: workflow,event,commit
          color: ${{ job.status == 'success' && 'good' || 'danger' }}
          channel: ci-cd-updates
