name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk

      - name: Build iOS IPA
        run: flutter build ios --no-codesign

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: App Build
          path: |
            build/app/outputs/apk/release/app-release.apk
            build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app

      - name: Send Slack notification
        uses: slack/webhook-action@v2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "New build is available!",
              "attachments": [
                {
                  "title": "Workflow: ${{ github.workflow }}",
                  "fields": [
                    {
                      "title": "Event",
                      "value": "${{ github.event_name }}"
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}"
                    }
                  ],
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}"
                }
              ]
            }
