name: Flutter CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: App Build
          path: build/app/outputs/apk/release/app-release.apk

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          text: |
            New build is available!
            Workflow: ${{ github.workflow }}
            Event: ${{ github.event_name }}
            Commit: ${{ github.sha }}
            Instructions: To download the APK build, go to the [Actions tab](../../actions) and locate the latest workflow run. Download the artifact named 'App Build'.
          channel: ci-cd-updates
          color: ${{ job.status == 'success' && 'good' || 'danger' }}
          
